# Generated by Django 5.1.7 on 2025-03-23 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_accounting', '0002_alter_user_password_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='number_of_department',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='software_accounting.department'),
            preserve_default=False,
        ),
    ]
