# Generated by Django 5.1.7 on 2025-03-24 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_accounting', '0003_department_user_email_device_number_of_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department_number',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='software_accounting.department', to_field='number'),
            preserve_default=False,
        ),
    ]
