# Generated by Django 5.1.7 on 2025-04-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_accounting', '0004_user_department_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
