# Generated by Django 5.1.7 on 2025-04-28 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_accounting', '0005_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='id_software',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='software_accounting.software'),
        ),
    ]
